### PR TITLE
Survey form

### PR DESCRIPTION
**Pull request by shogof**
I have created a survey form, which marks one of my initial endeavors. I am motivated to challenge myself to elevate my skills further.
Here are the project requirements:
- Page Title
- Brief Explanation
- Form Elements: Including Name Input, Email Input, Email Validation, Number Input, Number Validation, Number Range Validation, Labels, Placeholder Text, Dropdown with at least two options, Grouped Radio Buttons, Checkboxes, Textarea, and a Submit Button.

Feel free to review my project and provide feedback on any errors or areas for improvement, I stay calm amidst criticism, seeing it as a chance to grow. My commitment to improvement keeps me moving forward, regardless of challenges. Each critique is an opportunity to refine my skills further.

### CODE REVIEW

**Comment by ahzamir** [comment]
### Hi @shogof 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Copy your HTML file code and paste it to the freecodecamp website survey form project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

AlmostThereReachGIF

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Survey Form and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by shogof** [comment]
@ahzamir, @ahzia
To my esteemed teachers Ahmad Zamir Yousufi and Ahmad Zia Yousufi :)

I am deeply grateful for your valuable feedback since I received it. I have carefully reviewed your suggested changes and implemented them into my project. Thank you very much for taking the time to guide me.

Should there be any further issues or suggestions, please do not hesitate to inform me. Your guidance is greatly appreciated.

With utmost appreciation,
Shogofa Muradi

**Comment by ahzamir** [comment]
### Hi @iamfarhatsharefi 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Odin project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by shogof** [comment]
Thanks in advance Teacher :)

**Pull request merged**
